#!/usr/bin/env sh

: ${S3_ACCESS_KEY_ID}
: ${S3_BUCKET}
: ${S3_ENDPOINT}
: ${S3_REGION}
: ${S3_SECRET_ACCESS_KEY}

echo "user_allow_other" >> /etc/fuse.conf

mkdir -p \
    /etc/rclone \
    /mnt/rclone

cat << EOF >> /etc/rclone/rclone.conf
[remote]
type = s3
provider = Other
access_key_id = ${S3_ACCESS_KEY_ID}
endpoint = ${S3_ENDPOINT}
region = ${S3_REGION}
secret_access_key = ${S3_SECRET_ACCESS_KEY}
EOF
